/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PGV;

import DANGNHAP.ConnectToDB;
import DANGNHAP.DANGNHAP;
import DANGNHAP.User;
import java.awt.CardLayout;
import java.awt.Color;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.*;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author linhm
 */
public class NewJFrame extends javax.swing.JFrame {

    CardLayout cl = new CardLayout();
    static String USER_NAME = "";
    static String PASS_WORD = "";
    static ArrayList<User> listUser = new ArrayList<>();
    static ArrayList<Role> listRole = new ArrayList<>();
    static ArrayList<Table> listTable = new ArrayList<>();
    static ArrayList<StoredProcedured> listSP = new ArrayList<>();
    static ArrayList<Views> listViews = new ArrayList<>();
    static ArrayList<Login> listLoginRole = new ArrayList<>();
    DefaultTableModel dtm;
    

    public NewJFrame(String taiKhoan, String matKhau) {

        initComponents();
        setLocationRelativeTo(null);
        USER_NAME = taiKhoan;
        PASS_WORD = matKhau;
        getDataUser();

        for (User user : listUser) {
            lbHoTenGV.setText(user.getHoTen());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButton3 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButton4 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jButton5 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        WELCOM = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lbHoTenGV = new javax.swing.JLabel();
        TaoRole = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTenRole = new javax.swing.JTextField();
        btnTaoRole = new javax.swing.JButton();
        lbTenRole = new javax.swing.JLabel();
        CapQuyenChoRole = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbRole = new javax.swing.JComboBox<>();
        cbLoaiDoiTuong = new javax.swing.JComboBox<>();
        cbDoiTuong = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbQuyen = new javax.swing.JComboBox<>();
        jSeparator8 = new javax.swing.JSeparator();
        btnCapQuyenChoRole = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        TaoLogin = new javax.swing.JPanel();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnTaoLogin = new javax.swing.JButton();
        txtTenLogin = new javax.swing.JTextField();
        cbUserMapping = new javax.swing.JComboBox<>();
        cbMaUser = new javax.swing.JComboBox<>();
        txtMKLogin = new javax.swing.JPasswordField();
        lbLogin = new javax.swing.JLabel();
        lbMK = new javax.swing.JLabel();
        lbMaUser = new javax.swing.JLabel();
        lbTenUser = new javax.swing.JLabel();
        ThemXoaLoginVaoRole = new javax.swing.JPanel();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cbNameRole = new javax.swing.JComboBox<>();
        cbLogin = new javax.swing.JComboBox<>();
        jSeparator15 = new javax.swing.JSeparator();
        jButton8 = new javax.swing.JButton();
        jSeparator16 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbRoleLogin = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        txtLoginXoa = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtRoleXoa = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        cbDoiTuongThem = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        DoiMatKhau = new javax.swing.JPanel();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbLoginDoiMK = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        txtNewPW = new javax.swing.JPasswordField();
        txtConfirmPW = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        btnDoiMatKhau = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        cbDoiTuongDoiMK = new javax.swing.JComboBox<>();
        lbLoginDoiMK = new javax.swing.JLabel();
        lbNewPW = new javax.swing.JLabel();
        lbConfirmPW = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/-library-add_90110.png"))); // NOI18N
        jButton1.setText("        Tạo Role       ");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);
        jToolBar1.add(jSeparator1);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/library-books_117453.png"))); // NOI18N
        jButton2.setText("        Cấp quyền       ");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);
        jToolBar1.add(jSeparator2);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/adduser_añadir_3553.png"))); // NOI18N
        jButton3.setText("           Tạo Login        ");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);
        jToolBar1.add(jSeparator4);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/user_setting_settings_icon_148607.png"))); // NOI18N
        jButton4.setText("Thêm xóa Login    ");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);
        jToolBar1.add(jSeparator3);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/change_password_icon_154438.png"))); // NOI18N
        jButton5.setText("            Mật khẩu        ");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);
        jToolBar1.add(jSeparator5);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/log_in_icon_128822.png"))); // NOI18N
        jButton6.setText("        Đăng xuất        ");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.CardLayout());

        WELCOM.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel22.setText("CHÀO MỪNG ĐẾN VỚI PHÒNG GIÁO VỤ");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setText("Giảng viên:");

        lbHoTenGV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout WELCOMLayout = new javax.swing.GroupLayout(WELCOM);
        WELCOM.setLayout(WELCOMLayout);
        WELCOMLayout.setHorizontalGroup(
            WELCOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WELCOMLayout.createSequentialGroup()
                .addGroup(WELCOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WELCOMLayout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel23)
                        .addGap(47, 47, 47)
                        .addComponent(lbHoTenGV, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(WELCOMLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        WELCOMLayout.setVerticalGroup(
            WELCOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WELCOMLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel22)
                .addGap(71, 71, 71)
                .addGroup(WELCOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbHoTenGV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(257, Short.MAX_VALUE))
        );

        jPanel2.add(WELCOM, "card4");

        TaoRole.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel6.setText("TẠO ROLE");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Nhập tên Role:");

        txtTenRole.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnTaoRole.setBackground(new java.awt.Color(255, 255, 255));
        btnTaoRole.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTaoRole.setText("Thêm");
        btnTaoRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoRoleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TaoRoleLayout = new javax.swing.GroupLayout(TaoRole);
        TaoRole.setLayout(TaoRoleLayout);
        TaoRoleLayout.setHorizontalGroup(
            TaoRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator6)
            .addComponent(jSeparator7)
            .addGroup(TaoRoleLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(txtTenRole, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(257, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TaoRoleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TaoRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TaoRoleLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(364, 364, 364))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TaoRoleLayout.createSequentialGroup()
                        .addComponent(btnTaoRole, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(361, 361, 361))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TaoRoleLayout.createSequentialGroup()
                        .addComponent(lbTenRole, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(334, 334, 334))))
        );
        TaoRoleLayout.setVerticalGroup(
            TaoRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaoRoleLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addGap(36, 36, 36)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141)
                .addGroup(TaoRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTenRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(lbTenRole, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTaoRole)
                .addGap(37, 37, 37))
        );

        jPanel2.add(TaoRole, "card5");

        CapQuyenChoRole.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Chọn Role:");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Chọn loại đối tượng:");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Chọn đối tượng:");

        cbRole.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbRoleItemStateChanged(evt);
            }
        });

        cbLoaiDoiTuong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Table", "Stored Procedured", "Views" }));
        cbLoaiDoiTuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLoaiDoiTuongActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Chọn quyền:");

        btnCapQuyenChoRole.setBackground(new java.awt.Color(255, 255, 255));
        btnCapQuyenChoRole.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCapQuyenChoRole.setText("Cấp Quyền");
        btnCapQuyenChoRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapQuyenChoRoleActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel5.setText("CẤP QUYỀN CHO ROLE");

        javax.swing.GroupLayout CapQuyenChoRoleLayout = new javax.swing.GroupLayout(CapQuyenChoRole);
        CapQuyenChoRole.setLayout(CapQuyenChoRoleLayout);
        CapQuyenChoRoleLayout.setHorizontalGroup(
            CapQuyenChoRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator8)
            .addComponent(jSeparator9)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CapQuyenChoRoleLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(280, 280, 280))
            .addGroup(CapQuyenChoRoleLayout.createSequentialGroup()
                .addGroup(CapQuyenChoRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CapQuyenChoRoleLayout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addGroup(CapQuyenChoRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CapQuyenChoRoleLayout.createSequentialGroup()
                                .addGroup(CapQuyenChoRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(70, 70, 70)
                                .addGroup(CapQuyenChoRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbDoiTuong, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(CapQuyenChoRoleLayout.createSequentialGroup()
                                .addGroup(CapQuyenChoRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(41, 41, 41)
                                .addGroup(CapQuyenChoRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbRole, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbLoaiDoiTuong, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(CapQuyenChoRoleLayout.createSequentialGroup()
                        .addGap(391, 391, 391)
                        .addComponent(btnCapQuyenChoRole)))
                .addContainerGap(297, Short.MAX_VALUE))
        );
        CapQuyenChoRoleLayout.setVerticalGroup(
            CapQuyenChoRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CapQuyenChoRoleLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addGap(32, 32, 32)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(CapQuyenChoRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(CapQuyenChoRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbLoaiDoiTuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(CapQuyenChoRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDoiTuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(53, 53, 53)
                .addGroup(CapQuyenChoRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cbQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCapQuyenChoRole)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel2.add(CapQuyenChoRole, "card2");

        TaoLogin.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel8.setText("TẠO TÀI KHOẢN");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Tên đăng nhập:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Mật khẩu:");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Đối tượng:");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Mã:");

        btnTaoLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnTaoLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTaoLogin.setText("Thêm");
        btnTaoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoLoginActionPerformed(evt);
            }
        });

        txtTenLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cbUserMapping.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbUserMapping.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giảng viên", "Sinh viên" }));
        cbUserMapping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUserMappingActionPerformed(evt);
            }
        });

        cbMaUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbMaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMaUserActionPerformed(evt);
            }
        });

        txtMKLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lbTenUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout TaoLoginLayout = new javax.swing.GroupLayout(TaoLogin);
        TaoLogin.setLayout(TaoLoginLayout);
        TaoLoginLayout.setHorizontalGroup(
            TaoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator10)
            .addComponent(jSeparator11, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(TaoLoginLayout.createSequentialGroup()
                .addGroup(TaoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TaoLoginLayout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(jLabel8))
                    .addGroup(TaoLoginLayout.createSequentialGroup()
                        .addGap(385, 385, 385)
                        .addComponent(btnTaoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(341, Short.MAX_VALUE))
            .addGroup(TaoLoginLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addGroup(TaoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(35, 35, 35)
                .addGroup(TaoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTenLogin)
                    .addComponent(cbUserMapping, 0, 212, Short.MAX_VALUE)
                    .addComponent(cbMaUser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMKLogin)
                    .addComponent(lbLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbMK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbMaUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTenUser, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        TaoLoginLayout.setVerticalGroup(
            TaoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaoLoginLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addGap(30, 30, 30)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(TaoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTenLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(TaoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtMKLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbMK, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(TaoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbUserMapping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(TaoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TaoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(cbMaUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbTenUser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(lbMaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTaoLogin)
                .addGap(28, 28, 28))
        );

        jPanel2.add(TaoLogin, "card4");

        ThemXoaLoginVaoRole.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel17.setText("THÊM XÓA LOGIN VÀO ROLE");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Chọn Role:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Chọn Login:");

        cbNameRole.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbNameRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNameRoleActionPerformed(evt);
            }
        });

        cbLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLoginActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton8.setText("Thêm");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tbRoleLogin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tên Role", "Tên Login", "Họ tên"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbRoleLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbRoleLoginMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbRoleLogin);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Login:");

        txtLoginXoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLoginXoa.setToolTipText("");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("Role:");

        txtRoleXoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRoleXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoleXoaActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton9.setText("Xóa");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText("Đối Tượng:");

        cbDoiTuongThem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbDoiTuongThem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giảng viên", "Sinh viên" }));
        cbDoiTuongThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDoiTuongThemActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("Tìm kiếm theo tên:");

        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout ThemXoaLoginVaoRoleLayout = new javax.swing.GroupLayout(ThemXoaLoginVaoRole);
        ThemXoaLoginVaoRole.setLayout(ThemXoaLoginVaoRoleLayout);
        ThemXoaLoginVaoRoleLayout.setHorizontalGroup(
            ThemXoaLoginVaoRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator14)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThemXoaLoginVaoRoleLayout.createSequentialGroup()
                .addGroup(ThemXoaLoginVaoRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThemXoaLoginVaoRoleLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(ThemXoaLoginVaoRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel24))
                        .addGap(24, 24, 24)
                        .addGroup(ThemXoaLoginVaoRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbLogin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbDoiTuongThem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbNameRole, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ThemXoaLoginVaoRoleLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 296, Short.MAX_VALUE)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
            .addGroup(ThemXoaLoginVaoRoleLayout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThemXoaLoginVaoRoleLayout.createSequentialGroup()
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ThemXoaLoginVaoRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ThemXoaLoginVaoRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(ThemXoaLoginVaoRoleLayout.createSequentialGroup()
                            .addComponent(jLabel25)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ThemXoaLoginVaoRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ThemXoaLoginVaoRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(ThemXoaLoginVaoRoleLayout.createSequentialGroup()
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtRoleXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(ThemXoaLoginVaoRoleLayout.createSequentialGroup()
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(75, 75, 75)
                                    .addComponent(txtLoginXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        ThemXoaLoginVaoRoleLayout.setVerticalGroup(
            ThemXoaLoginVaoRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThemXoaLoginVaoRoleLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(ThemXoaLoginVaoRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThemXoaLoginVaoRoleLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(ThemXoaLoginVaoRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ThemXoaLoginVaoRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLoginXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(ThemXoaLoginVaoRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(txtRoleXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))
                    .addGroup(ThemXoaLoginVaoRoleLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(ThemXoaLoginVaoRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(cbNameRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ThemXoaLoginVaoRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(cbDoiTuongThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(ThemXoaLoginVaoRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(98, 98, 98)))
                .addGroup(ThemXoaLoginVaoRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ThemXoaLoginVaoRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addGap(28, 28, 28))
        );

        jPanel2.add(ThemXoaLoginVaoRole, "card7");

        DoiMatKhau.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel13.setText("THAY ĐỔI MẬT KHẨU");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Chọn tài khoản:");

        cbLoginDoiMK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Nhập mật khẩu mới:");

        txtNewPW.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtConfirmPW.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Nhập lại mật khẩu mới:");

        btnDoiMatKhau.setBackground(new java.awt.Color(255, 255, 255));
        btnDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDoiMatKhau.setText("Xác nhận");
        btnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMatKhauActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setText("Chọn đối tượng");

        cbDoiTuongDoiMK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbDoiTuongDoiMK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giảng viên", "Sinh viên" }));
        cbDoiTuongDoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDoiTuongDoiMKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DoiMatKhauLayout = new javax.swing.GroupLayout(DoiMatKhau);
        DoiMatKhau.setLayout(DoiMatKhauLayout);
        DoiMatKhauLayout.setHorizontalGroup(
            DoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator12)
            .addComponent(jSeparator13)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DoiMatKhauLayout.createSequentialGroup()
                .addGap(0, 317, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(285, 285, 285))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DoiMatKhauLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDoiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(356, 356, 356))
            .addGroup(DoiMatKhauLayout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addGroup(DoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel14)
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(DoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbConfirmPW, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(lbNewPW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbLoginDoiMK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbLoginDoiMK, 0, 204, Short.MAX_VALUE)
                    .addComponent(txtNewPW)
                    .addComponent(txtConfirmPW)
                    .addComponent(cbDoiTuongDoiMK, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DoiMatKhauLayout.setVerticalGroup(
            DoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoiMatKhauLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel13)
                .addGap(32, 32, 32)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(DoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(cbDoiTuongDoiMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(DoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbLoginDoiMK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbLoginDoiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(DoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNewPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(10, 10, 10)
                .addComponent(lbNewPW, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtConfirmPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(lbConfirmPW, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnDoiMatKhau)
                .addGap(45, 45, 45))
        );

        jPanel2.add(DoiMatKhau, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void getDataUser() {
        listUser.clear();
        try {
            Connection conn = ConnectToDB.getConnection(USER_NAME, PASS_WORD);
            CallableStatement ps = conn.prepareCall("{call SP_DANGNHAP (?)}");
            ps.setString(1, USER_NAME);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {

                User user = new User(rs.getString(1), rs.getString(2), rs.getString(3));
                listUser.add(user);
            }
            rs.close();
            ps.close();
        } catch (SQLException ex) {

        }

    }

    public void getDataRoleName() {
        listRole.clear();
        try {
            Connection conn = ConnectToDB.getConnection(USER_NAME, PASS_WORD);
            PreparedStatement ps = conn.prepareStatement("select * from V_LayRolename");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Role role = new Role(rs.getString(1));
                listRole.add(role);
            }
            rs.close();
            ps.close();
        } catch (SQLException ex) {
            System.out.println(" V_LayRolename khong thanh cong");
        }
    }

    public void getDataTableName() {
        listTable.clear();
        try {
            Connection conn = ConnectToDB.getConnection(USER_NAME, PASS_WORD);
            PreparedStatement ps = conn.prepareStatement("select * from V_LayTatCaTable");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Table table = new Table(rs.getString(1));
                listTable.add(table);
            }
            rs.close();
            ps.close();
        } catch (SQLException ex) {
            System.out.println(" V_LayTatCaTable khong thanh cong");
        }
    }

    public void getDataSPName() {
        listSP.clear();
        try {
            Connection conn = ConnectToDB.getConnection(USER_NAME, PASS_WORD);
            PreparedStatement ps = conn.prepareStatement("select * from V_LaySP");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                StoredProcedured sp = new StoredProcedured(rs.getString(1));
                listSP.add(sp);
            }
            rs.close();
            ps.close();
        } catch (SQLException ex) {
            System.out.println(" V_LaySP khong thanh cong");
        }
    }

    public void getDataViewsName() {
        listViews.clear();
        try {
            Connection conn = ConnectToDB.getConnection(USER_NAME, PASS_WORD);
            PreparedStatement ps = conn.prepareStatement("select * from V_LayViews");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Views views = new Views(rs.getString(1));
                listViews.add(views);
            }
            rs.close();
            ps.close();
        } catch (SQLException ex) {
            System.out.println(" V_LayViews khong thanh cong");
        }
    }

    public void loadDataCbRole() {
        cbNameRole.removeAllItems();
        cbRole.removeAllItems();
        getDataRoleName();
        for (Role role : listRole) {
            cbRole.addItem(role.getRoleName());
            cbNameRole.addItem(role.getRoleName());
        }
    }

    public void loadDataTableRoleLogin() {
        dtm = (DefaultTableModel) tbRoleLogin.getModel();
        dtm.setNumRows(0);
        Connection connection = ConnectToDB.getConnection(USER_NAME, PASS_WORD);
        try {
            PreparedStatement ps = connection.prepareStatement("select * from V_LayRoleName_LGname_Hoten");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Vector vt = new Vector();
                vt.add(rs.getString(1));
                vt.add(rs.getString(2));
                vt.add(rs.getString(3));
                dtm.addRow(vt);
            }
            rs.close();
            ps.close();
            connection.close();
        } catch (Exception e) {
            System.out.println("E: " + e);
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jPanel2.removeAll();
        jPanel2.add(CapQuyenChoRole);
        jPanel2.repaint();
        jPanel2.revalidate();
        loadDataCbRole();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jPanel2.removeAll();
        jPanel2.add(TaoRole);
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jPanel2.removeAll();
        jPanel2.add(TaoLogin);
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jPanel2.removeAll();
        jPanel2.add(ThemXoaLoginVaoRole);
        jPanel2.repaint();
        jPanel2.revalidate();
        loadDataCbRole();
        loadDataTableRoleLogin();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jPanel2.removeAll();
        jPanel2.add(DoiMatKhau);
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new DANGNHAP().setVisible(true);

    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnTaoRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoRoleActionPerformed
        boolean check = true;
        if (txtTenRole.getText().length() == 0) {
            lbTenRole.setForeground(Color.red);
            lbTenRole.setText("Không được bỏ trống");
            check = false;
            txtTenRole.requestFocus();
            return;
        } else {
            lbTenRole.setForeground(Color.white);
        }
        getDataRoleName();
        for (Role role : listRole) {

            if (txtTenRole.getText().equalsIgnoreCase(role.getRoleName())) {
                lbTenRole.setForeground(Color.red);
                lbTenRole.setText("Tên Role đã tồn tại");
                check = false;
                txtTenRole.requestFocus();
                return;
            } else {
                lbTenRole.setForeground(Color.white);
            }
        }
        if (check) {
            try {
                Connection conn = ConnectToDB.getConnection(USER_NAME, PASS_WORD);
                CallableStatement ps = conn.prepareCall("{call SP_TAO_ROLE (?)}");
                ps.setString(1, txtTenRole.getText().toUpperCase());
                ps.execute();
                ps.close();
                JOptionPane.showMessageDialog(this, "Tạo Role thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

            } catch (SQLException ex) {
                System.out.println("Loi goi SP_TAO_ROLE");
            }
            txtTenRole.setText("");
        }
    }//GEN-LAST:event_btnTaoRoleActionPerformed

    private void txtRoleXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoleXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoleXoaActionPerformed

    public String[] quyenTable_Views() {
        String[] quyen = new String[]{"All", "Alter", "Delete", "Insert", "References", "Select",
            "Update"};
        return quyen;
    }

    public String[] quyenStoredProcedured() {
        String[] quyen = new String[]{"Alter", "Execute", "Take Ownership", "View definition"};
        return quyen;
    }

    private void cbLoaiDoiTuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLoaiDoiTuongActionPerformed
        if (cbLoaiDoiTuong.getSelectedItem() != null) {
            String loai = cbLoaiDoiTuong.getSelectedItem().toString();
            if (loai.equals("Table")) {
                cbDoiTuong.removeAllItems();
                cbQuyen.removeAllItems();
                getDataTableName();
                for (Table table : listTable) {
                    cbDoiTuong.addItem(table.getTenTable());
                }
                for (String s : quyenTable_Views()) {
                    cbQuyen.addItem(s);
                }
            } else if (loai.equals("Stored Procedured")) {
                cbDoiTuong.removeAllItems();
                cbQuyen.removeAllItems();
                getDataSPName();
                for (StoredProcedured sp : listSP) {
                    cbDoiTuong.addItem(sp.getTenSP());
                }
                for (String s : quyenStoredProcedured()) {
                    cbQuyen.addItem(s);
                }
            } else {
                cbDoiTuong.removeAllItems();
                cbQuyen.removeAllItems();
                getDataViewsName();
                for (Views views : listViews) {
                    cbDoiTuong.addItem(views.getTenViews());
                }
                for (String s : quyenTable_Views()) {
                    cbQuyen.addItem(s);
                }
            }

        }
    }//GEN-LAST:event_cbLoaiDoiTuongActionPerformed

    private void cbRoleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbRoleItemStateChanged

    }//GEN-LAST:event_cbRoleItemStateChanged

    private void btnCapQuyenChoRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapQuyenChoRoleActionPerformed
        try {
            Connection conn = ConnectToDB.getConnection(USER_NAME, PASS_WORD);
            CallableStatement ps = conn.prepareCall("{call SP_CAPQUYENCHOROLE (?,?,?)}");
            ps.setString(1, cbRole.getSelectedItem().toString());
            ps.setString(2, cbQuyen.getSelectedItem().toString());
            ps.setString(3, cbDoiTuong.getSelectedItem().toString());
            ps.execute();
            ps.close();
            JOptionPane.showMessageDialog(this, "Cấp quyền thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi cấp quyền");
            System.out.println("Loi goi SP_CAPQUYENCHOROLE");
        }
    }//GEN-LAST:event_btnCapQuyenChoRoleActionPerformed

    private void cbUserMappingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUserMappingActionPerformed
        if (cbUserMapping.getSelectedItem() != null) {
            String loai = cbUserMapping.getSelectedItem().toString();
            if (loai.equals("Giảng viên")) {
                cbMaUser.removeAllItems();
                try {
                    Connection conn = ConnectToDB.getConnection(USER_NAME, PASS_WORD);
                    PreparedStatement ps = conn.prepareStatement("Select * from V_DSGV_CTTK");
                    ResultSet rs = ps.executeQuery();
                    while (rs.next()) {
                        cbMaUser.addItem(rs.getString(1));
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            } else {
                cbMaUser.removeAllItems();
                try {
                    Connection conn = ConnectToDB.getConnection(USER_NAME, PASS_WORD);
                    PreparedStatement ps = conn.prepareStatement("Select * from V_DSSV_CTTK");
                    ResultSet rs = ps.executeQuery();
                    while (rs.next()) {
                        cbMaUser.addItem(rs.getString(1));
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }

        }
    }//GEN-LAST:event_cbUserMappingActionPerformed

    private void cbNameRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNameRoleActionPerformed

//        if (cbNameRole.getSelectedItem() != null) {
//            String tenRole = cbNameRole.getSelectedItem().toString();
//            cbLogin.removeAllItems();
//            listLoginRole.clear();
//            try {
//                Connection conn = ConnectToDB.getConnection(USER_NAME, PASS_WORD);
//                CallableStatement ps = conn.prepareCall("{call SP_LayLGnameThuocRole (?)}");
//                ps.setString(1, tenRole);
//                ResultSet rs = ps.executeQuery();
//                while (rs.next()) {
//                    Login login = new Login(rs.getString(1), rs.getString(2));
//                    listLoginRole.add(login);
//                }
//            } catch (Exception e) {
//            }
//        }

    }//GEN-LAST:event_cbNameRoleActionPerformed

    public boolean checkKhoangTrang(String a) {
        return a.matches("\\w+");
    }

    private void btnTaoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoLoginActionPerformed
        boolean check = true;
        if (txtTenLogin.getText().length() == 0) {
            lbLogin.setForeground(Color.red);
            lbLogin.setText("Tên đăng nhập không được bỏ trống");
            check = false;
            txtTenLogin.requestFocus();
            return;
        } else {
            lbLogin.setForeground(Color.white);
        }
        if (!checkKhoangTrang(txtTenLogin.getText().trim())) {
            lbLogin.setForeground(Color.red);
            lbLogin.setText("Tên đăng nhập không chứa khoảng trắng");
            check = false;
            txtTenLogin.requestFocus();
            return;
        } else {
            lbLogin.setForeground(Color.white);
        }
        if (check) {

            try {
                Connection conn = ConnectToDB.getConnection(USER_NAME, PASS_WORD);
                CallableStatement ps = conn.prepareCall("{Call SP_TAOLOGIN (?,?,?,?)}");
                ps.setString(1, txtTenLogin.getText().toUpperCase());
                ps.setString(2, String.valueOf(txtMKLogin.getPassword()));
                ps.setString(3, cbMaUser.getSelectedItem().toString());
                ps.registerOutParameter(4, Types.INTEGER);

                ps.execute();

                int n = ps.getInt(4);

                if (n == 0) {
                    JOptionPane.showMessageDialog(this, "Tạo tài khoản thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

                } else if (n == 1) {
                    JOptionPane.showMessageDialog(this, "Trùng tên đăng nhập");
                } else {
                    JOptionPane.showMessageDialog(this, "Người dùng đã có tài khoản");
                }

                ps.close();

            } catch (SQLException se) {
                se.printStackTrace();
                System.out.println(" Lỗi Dang Ki Tai Khoan");
            }

        }
        txtTenLogin.setText("");
        txtMKLogin.setText("");
        cbMaUser.removeAllItems();
    }//GEN-LAST:event_btnTaoLoginActionPerformed

    private void cbLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLoginActionPerformed

    }//GEN-LAST:event_cbLoginActionPerformed

    private void cbDoiTuongThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDoiTuongThemActionPerformed
       // if (cbDoiTuongThem.getSelectedItem() != null) {
            String loai = cbDoiTuongThem.getSelectedItem().toString();
            if (loai.equals("Giảng viên")) {
                cbLogin.removeAllItems();
                try {
                    Connection conn = ConnectToDB.getConnection(USER_NAME, PASS_WORD);
                    PreparedStatement ps = conn.prepareStatement("Select * from V_LoginChuaThuocRole_GV");
                    ResultSet rs = ps.executeQuery();
                    while (rs.next()) {                      
                        cbLogin.addItem(rs.getString(1));
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            } else {
                cbLogin.removeAllItems();
                try {
                    Connection conn = ConnectToDB.getConnection(USER_NAME, PASS_WORD);
                    PreparedStatement ps = conn.prepareStatement("Select * from V_LoginChuaThuocRole_SV");
                    ResultSet rs = ps.executeQuery();
                    while (rs.next()) {                      
                        cbLogin.addItem(rs.getString(1));
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }

       // }
    }//GEN-LAST:event_cbDoiTuongThemActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (cbLogin.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn tài khoản", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                Connection conn = ConnectToDB.getConnection(USER_NAME, PASS_WORD);
                CallableStatement ps = conn.prepareCall("{Call SP_ThemLoginVaoRole (?,?)}");
                ps.setString(1, cbLogin.getSelectedItem().toString());
                ps.setString(2, cbNameRole.getSelectedItem().toString());
                ps.execute();
                JOptionPane.showMessageDialog(this, "Thêm tài khoản vào Role thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                ps.close();

            } catch (SQLException se) {
                se.printStackTrace();
                System.out.println(" Lỗi Thêm");
            }
            cbLogin.removeAllItems();
            loadDataTableRoleLogin();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txtTimKiemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyTyped
        String s = txtTimKiem.getText();
        s = s + evt.getKeyChar();
        s = s.trim();
        dtm = (DefaultTableModel) tbRoleLogin.getModel();
        dtm.setNumRows(0);
        Connection connection = ConnectToDB.getConnection(USER_NAME, PASS_WORD);
        try {
            PreparedStatement ps = connection.prepareStatement("select * from V_LayRoleName_LGname_Hoten where HOTEN like  N'%" + s + "%'");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Vector vt = new Vector();
                vt.add(rs.getString(1));
                vt.add(rs.getString(2));
                vt.add(rs.getString(3));
                dtm.addRow(vt);
            }
            rs.close();
            ps.close();
            connection.close();
        } catch (Exception e) {
            System.out.println("E: " + e);
        }
    }//GEN-LAST:event_txtTimKiemKeyTyped

    private void tbRoleLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRoleLoginMouseClicked

        dtm = (DefaultTableModel) tbRoleLogin.getModel();

        int j = tbRoleLogin.getSelectedRow();

        int i = tbRoleLogin.convertRowIndexToModel(j);
        System.out.println(dtm.getValueAt(i, 1).toString());
        if (dtm.getValueAt(i, 1).toString().equalsIgnoreCase(USER_NAME)) {
            JOptionPane.showMessageDialog(this, "Không thể xóa tài khoản đang sử dụng");
        } else {
            txtLoginXoa.setText(dtm.getValueAt(i, 1).toString());
            txtRoleXoa.setText(dtm.getValueAt(i, 0).toString());
        }
    }//GEN-LAST:event_tbRoleLoginMouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (txtLoginXoa.getText().equals("") || txtRoleXoa.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chon đối tượng cần xóa!");
        } else if(JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa "+txtLoginXoa.getText()+" khỏi "+txtRoleXoa.getText()+" không?","Thông báo", JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION){
            try {
                Connection conn = ConnectToDB.getConnection(USER_NAME, PASS_WORD);
                CallableStatement ps = conn.prepareCall("{call SP_XoaLoginKhoiRole (?,?)}");
                ps.setString(1, txtRoleXoa.getText());
                ps.setString(2, txtLoginXoa.getText());
                ps.execute();
                JOptionPane.showMessageDialog(this, "Đã xóa Login khỏi Role", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                ps.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }else{
            return;
        }
        txtTimKiem.setText("");
        txtRoleXoa.setText("");
        txtLoginXoa.setText("");
        loadDataTableRoleLogin();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void cbDoiTuongDoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDoiTuongDoiMKActionPerformed
        if (cbDoiTuongDoiMK.getSelectedItem() != null) {
            String loai = cbDoiTuongDoiMK.getSelectedItem().toString();
            if (loai.equals("Giảng viên")) {
                cbLoginDoiMK.removeAllItems();
                try {
                    Connection conn = ConnectToDB.getConnection(USER_NAME, PASS_WORD);
                    PreparedStatement ps = conn.prepareStatement("Select * from V_LayLoginname_GV");
                    ResultSet rs = ps.executeQuery();
                    while (rs.next()) {
                        cbLoginDoiMK.addItem(rs.getString(1));
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            } else {
                cbLoginDoiMK.removeAllItems();
                try {
                    Connection conn = ConnectToDB.getConnection(USER_NAME, PASS_WORD);
                    PreparedStatement ps = conn.prepareStatement("Select * from V_LayLoginname_SV");
                    ResultSet rs = ps.executeQuery();
                    while (rs.next()) {
                        cbLoginDoiMK.addItem(rs.getString(1));
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }

        }
    }//GEN-LAST:event_cbDoiTuongDoiMKActionPerformed

    private void btnDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMatKhauActionPerformed
        boolean check = true;
        String newPW = String.valueOf(txtNewPW.getPassword());
        String confirmPW = String.valueOf(txtConfirmPW.getPassword());
        if (cbLoginDoiMK.getSelectedItem() == null) {
            lbLoginDoiMK.setForeground(Color.red);
            lbLoginDoiMK.setText("Tên tài khoản không được bỏ trống");
            check = false;
            cbLoginDoiMK.requestFocus();
            return;
        } else {
            lbLoginDoiMK.setForeground(Color.white);
        }
        if (newPW.length() == 0) {
            lbNewPW.setForeground(Color.red);
            lbNewPW.setText("Mật khẩu không được bỏ trống");
            check = false;
            txtNewPW.requestFocus();
            return;
        } else {
            lbNewPW.setForeground(Color.white);
        }
        if (!checkKhoangTrang(newPW)) {
            lbNewPW.setForeground(Color.red);
            lbNewPW.setText("Mật khẩu không được có khoảng trắng");
            check = false;
            txtNewPW.requestFocus();
            return;
        } else {
            lbNewPW.setForeground(Color.white);
        }

        if (!confirmPW.equals(newPW)) {
            lbConfirmPW.setForeground(Color.red);
            lbConfirmPW.setText("Mật khẩu xác nhận không hợp lệ");
            check = false;
            txtConfirmPW.requestFocus();
            return;
        } else {
            lbConfirmPW.setForeground(Color.white);
        }
        if (check) {
            try {
                Connection conn = ConnectToDB.getConnection(USER_NAME, PASS_WORD);
                CallableStatement ps = conn.prepareCall("{call SP_DOIMATKHAU (?,?)}");
                ps.setString(1, cbLoginDoiMK.getSelectedItem().toString());
                ps.setString(2, String.valueOf(txtNewPW.getPassword()));
                ps.execute();
                if (cbLoginDoiMK.getSelectedItem().toString().equalsIgnoreCase(USER_NAME)) {
                    JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công! \n"
                            + "\n"
                            + " Vui lòng đăng nhập lại", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    new DANGNHAP().setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Thay đổi mật khẩu thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }
                ps.close();
            } catch (Exception e) {
                e.printStackTrace();
            }

            cbLoginDoiMK.removeAllItems();
            txtNewPW.setText("");
            txtConfirmPW.setText("");

        }

    }//GEN-LAST:event_btnDoiMatKhauActionPerformed

    private void cbMaUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMaUserActionPerformed
        if (cbMaUser.getSelectedItem() != null) {
            String ma = cbMaUser.getSelectedItem().toString();
            if (cbUserMapping.getSelectedItem().toString().equals("Giảng viên")) {
                try {
                    Connection conn = ConnectToDB.getConnection(USER_NAME, PASS_WORD);
                    PreparedStatement ps = conn.prepareStatement("Select HOTEN = HO + ' ' + TEN from GIANGVIEN where MAGV = ?");
                    ps.setString(1, ma);
                    ResultSet rs = ps.executeQuery();
                    if (rs.next()) {
                        lbTenUser.setText(rs.getString(1));
                    }
                } catch (Exception e) {
                }
            } else {
                try {
                    Connection conn = ConnectToDB.getConnection(USER_NAME, PASS_WORD);
                    PreparedStatement ps = conn.prepareStatement("Select HOTEN = HO + ' ' + TEN from SINHVIEN where MASV = ?");
                    ps.setString(1, ma);
                    ResultSet rs = ps.executeQuery();
                    if (rs.next()) {
                        lbTenUser.setText(rs.getString(1));
                    }
                } catch (Exception e) {
                }
            }
        }
    }//GEN-LAST:event_cbMaUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new NewJFrame(p).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CapQuyenChoRole;
    private javax.swing.JPanel DoiMatKhau;
    private javax.swing.JPanel TaoLogin;
    private javax.swing.JPanel TaoRole;
    private javax.swing.JPanel ThemXoaLoginVaoRole;
    private javax.swing.JPanel WELCOM;
    private javax.swing.JButton btnCapQuyenChoRole;
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JButton btnTaoLogin;
    private javax.swing.JButton btnTaoRole;
    private javax.swing.JComboBox<String> cbDoiTuong;
    private javax.swing.JComboBox<String> cbDoiTuongDoiMK;
    private javax.swing.JComboBox<String> cbDoiTuongThem;
    private javax.swing.JComboBox<String> cbLoaiDoiTuong;
    private javax.swing.JComboBox<String> cbLogin;
    private javax.swing.JComboBox<String> cbLoginDoiMK;
    private javax.swing.JComboBox<String> cbMaUser;
    private javax.swing.JComboBox<String> cbNameRole;
    private javax.swing.JComboBox<String> cbQuyen;
    private javax.swing.JComboBox<String> cbRole;
    private javax.swing.JComboBox<String> cbUserMapping;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbConfirmPW;
    private javax.swing.JLabel lbHoTenGV;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JLabel lbLoginDoiMK;
    private javax.swing.JLabel lbMK;
    private javax.swing.JLabel lbMaUser;
    private javax.swing.JLabel lbNewPW;
    private javax.swing.JLabel lbTenRole;
    private javax.swing.JLabel lbTenUser;
    private javax.swing.JTable tbRoleLogin;
    private javax.swing.JPasswordField txtConfirmPW;
    private javax.swing.JTextField txtLoginXoa;
    private javax.swing.JPasswordField txtMKLogin;
    private javax.swing.JPasswordField txtNewPW;
    private javax.swing.JTextField txtRoleXoa;
    private javax.swing.JTextField txtTenLogin;
    private javax.swing.JTextField txtTenRole;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
